version: '3.8'

services:
  app:
    build: .
    restart: always
    volumes:
      - ./app:/app  # Монтируем локальную папку с кодом в контейнер (для разработки)
    expose:
      - "8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://username:password@localhost/dbname
    network_mode: host

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /tmp/pgdata:/var/lib/postgresql/data
    network_mode: host

